version: '3.8'

services:
  pulsecare-api:
    build: .
    container_name: pulsecare_ehr_api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
    restart: always
